import MarkQustions from "./markQustions";
import type { Metadata } from "next";
import RightContent from "./rightContent";

export const metadata: Metadata = {
  title: "Home page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <div className="flex-grow w-full max-w-full mx-auto xl:px-0 lg:flex">
        {/* Left sidebar & main wrapper */}
        <div className="flex-1 min-w-0 bg-white xl:flex">
          <div className="bg-white lg:min-w-0 lg:flex-1">
            <div className="h-full py-0 px-0 sm:px-0 lg:px-0">
              {/* Start main area*/}
              <div className="relative h-full" style={{ minHeight: "36rem" }}>
                {/* hfg */}
                {children}
                {/* <div className="absolute inset-0 border-2 border-gray-200 border-dashed rounded-lg" /> */}
              </div>
              {/* End main area */}
            </div>
          </div>
        </div>

        <div className="bg-gray-50 pr-0 sm:pr-6 lg:pr-8 lg:flex-shrink-0 lg:border-l lg:border-gray-200 xl:pr-0">
          <div className="h-full pl-0 py-0 lg:w-80">
            {/* Start right column area */}
            <div className="h-full relative p-2" style={{ minHeight: "16rem" }}>
              <RightContent />
              <MarkQustions />
            </div>
            {/* End right column area */}
          </div>
        </div>
      </div>
    </>
  );
}

// const Questions = () => {
//     for (let i = 0; i < 100; i++) {
//       rows.push(<div className="w-5 h-5 bg-green-500 rounded-full shadow" />);
//     }
//     return rows;
//   };
